project_id = "lhknojwrwjjsymokgpzg"

[functions.summarize-requisition]
verify_jwt = false

[functions.shorten-description]
verify_jwt = false

[functions.bulk-import-users]
verify_jwt = true

[functions.bulk-import-suppliers]
verify_jwt = true