project_id = "lhknojwrwjjsymokgpzg"

[functions.summarize-requisition]
verify_jwt = false

[functions.shorten-description]
verify_jwt = false

[functions.bulk-import-users]
verify_jwt = true

[functions.bulk-import-suppliers]
verify_jwt = true

[functions.notify-requisition-submitted]
verify_jwt = false

[functions.notify-hod-approval]
verify_jwt = false

[functions.notify-hod-payment]
verify_jwt = false

[functions.notify-accountant]
verify_jwt = false

[functions.cleanup-requisitions]
verify_jwt = true
